config/routes.rb
Newspapers::Application.routes.draw do

  resources :newspapers do
    resources :subscription_plans
  end
  resources :users
  

end

app/models/newspaper.rb
class Newspaper < ActiveRecord::Base
  attr_accessible :editor, :title, :subscription_plans_attributes
  has_many :subscription_plans, inverse_of: :newspaper
  accepts_nested_attributes_for :subscription_plans, reject_if: :all_blank
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  attr_accessible :subscription_plan_id, :user_id
  belongs_to :subscription_plan
  belongs_to :user
end

app/models/subscription_plan.rb
class SubscriptionPlan < ActiveRecord::Base
  attr_accessible :daily, :price
  validates :price, presence: true
  validates_inclusion_of :daily, in: [true, false]
  belongs_to :newspaper
  has_many :subscriptions
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :subscription_plan_ids
  has_many :subscriptions
  has_many :subscription_plans, :through => :subscriptions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/newspapers_controller.rb
class NewspapersController < ApplicationController

  def show
    @newspaper = Newspaper.find(params[:id])
    @subscription_plans = @newspaper.subscription_plans
  end

  def create
    @newspaper = Newspaper.new(params[:newspaper])
    if @newspaper.save
      redirect_to newspaper_url(@newspaper.id)
    else
      render :new
    end
  end
  
  def show
    @newspaper = Newspaper.find(params[:id])
    @subscription_plans = @newspaper.subscription_plans
  end
  
  def index
    @newspapers = Newspaper.all
  end

end

app/controllers/subscription_plans_controller.rb
class SubscriptionPlansController < ApplicationController

  def new
    @newspaper = Newspaper.find(params[:newspaper_id])
    @subscription_plan = SubscriptionPlan.new
  end
  
  def create
    @newspaper = Newspaper.find(params[:newspaper_id])
    @subscription_plan = SubscriptionPlan.new(params[:subscription_plan])
    if @subscription_plan.save
      @subscription_plan.newspaper_id = @newspaper.id
      @subscription_plan.save
      redirect_to newspaper_url(@newspaper.id)
    else
      render :new
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user][:id])
    if @user.save
      flash[:notices] = "user's subscriptions saved successfully!"
      redirect_to newspapers_url
    else
      render :new
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/newspapers_helper.rb
module NewspapersHelper
end

app/helpers/subscription_plans_helper.rb
module SubscriptionPlansHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Newspapers</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/newspapers/index.html.erb
<h2>All Newspapers</h2>

<% @newspapers.each do |paper| %>

<ul>
  <li>Title: <%= paper.title %></li>
  <li>Editor: <%= paper.editor %></li>
</ul>

<% end %>

app/views/newspapers/new.html.erb
<h2>New Newspaper Form</h2>

<form action="<%= newspapers_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  
  <label>Title
    <input type="text" name="newspaper[title]">
  </label>
  <label>Editor
    <input type="text" name="newspaper[editor]">
  </label>


  <h2>Add some subscription plans too:</h2>
  
  <% 3.times do |i| %>
  <h4>Subscription Plan <%= i + 1 %>:</h4>
    <label>Price
      <input type="text" name="<%= "newspaper[subscription_plans_attributes][#{i}][price]" %>">
    </label>
    <label>Daily
      <input type="radio" name="<%= "newspaper[subscription_plans_attributes][#{i}][daily]" %>" value="true">
    </label>

    <label>Weekly
      <input type="radio" name="<%= "newspaper[subscription_plans_attributes][#{i}][daily]" %>" value="false">
    </label>
    <br>
  <% end %>

  <input type="submit" value="Go">


</form>

app/views/newspapers/show.html.erb
<h2>Available Subscription Plans</h2>
<h2>for the newspaper: <%= @newspaper.title %></h2>

<% if @subscription_plans %>

  <% @subscription_plans.each_with_index do |plan, i| %>
  <h4><%= "Subscription Plan option #{i+1}:" %></h4>
  <ul>
    <li>Price: $<%= plan.price %></li>
    <li><%= plan.daily ? "Daily" : "Weekly" %></li>
  </ul>
  <% end %>

<% end %>

app/views/subscription_plans/new.html.erb
<h2>Make a New Subscription Plan</h2>

<form action="<%= newspaper_subscription_plans_url(@newspaper.id) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  
  <label>Price
    <input type="text" name="subscription_plan[price]">
  </label>
  <br>
  <label>Daily
    <input type="radio" name="subscription_plan[daily]" value="true">
  </label>
  <label>Weekly 
    <input type="radio" name="subscription_plan[daily]" value="false">
  </label>
  <br>
  <input type="submit" value="Go">
</form>

app/views/users/new.html.erb
<h2>Sign Up for newspaper subscriptions</h2>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Name
    <input type="text" name="user[name]">
  </label>
  
  <% Newspaper.all.each_with_index do |paper, i| %>
  <h4>paper.title</h4>
  <select name="<%= "user[subscription_plans_ids][]" %>">
    <% paper.subscription_plans.each do |plan| %>
      <option value="<%= plan.id %>"><%= plan.price %>, <%= plan.daily ? "daily" : "weekly" %></option>
    <% end %>
    
    
  </select>
  <br>
  <% end %>
  
  <input type="submit" value="Go">
  
</form>